[project]
name = "cnf-descent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "equinox>=0.11.10",
    "jax[cuda12-pip]>=0.4.36",
    "matplotlib>=3.9.3",
    "optax>=0.2.4",
]
